### ISSUE TITLE
我寻思着恁也不是拆腻子逼吗？

### ISSUE THREAD

**Issue by logojackmowo-gh** [opengl106/project_fcf#1]
自己身为拆腻子却要屏蔽拆腻子，真有你的

**Comment by ESUAdmin** [comment]
在？看看李泽航的中文推特大全？

如果恁的单一用途账号仅仅是用来辱骂，把GH当作百度贴吧，那么我局的恁趁早被 report abuse 比较 ao。

**Comment by logojackmowo-gh** [comment]
> 在？看看李泽航的中文推特大全？
> 
> 如果恁的单一用途账号仅仅是用来辱骂，把GH当作百度贴吧，那么我局的恁趁早被 report abuse 比较 ao。

report就report吧，您GH账号不也是今天刚注册的吗
