### ISSUE TITLE
Satan love THOU,假判倭瓜壬

### ISSUE THREAD

**Issue by ghost** [opengl106/project_fcf#5]
**敢在外网上蹦跶，有胆回来，Ah Q?精神胜利法？

**Comment by ESUAdmin** [comment]
这里不会屏蔽，不用打星号，乐

小鬼们想把esu也玩成dssq，可以，那光复恶俗时代革命的重任就交给恁们啦。

**Comment by qq435672196** [comment]
> 这里不会屏蔽，不用打星号，乐
> 
> 小鬼们想把esu也玩成dssq，可以，那光复恶俗时代革命的重任就交给恁们啦。

打星号是为了让你构思骂恁的两个字，不是屏蔽

**Comment by ESUAdmin** [comment]
> > 这里不会屏蔽，不用打星号，乐
> > 小鬼们想把esu也玩成dssq，可以，那光复恶俗时代革命的重任就交给恁们啦。
> 
> 打星号是为了让你构思骂恁的那两个字，不是屏蔽。

那俺把这两个字理解成“野爹”了，不错

**Comment by opengl106** [comment]
Closed due to not updated for 1 year.
